/**
 * App.tsx — NHAI Datalake 3.0
 *
 * Root component. Manages all screens:
 *  - Onboarding    (first launch slider)
 *  - Home          (dashboard + action buttons)
 *  - Register      (camera registration flow)
 *  - Authenticate  (camera auth flow)
 *  - Attendance    (attendance log list)
 *  - Users         (registered users management)
 *  - Help          (help topics & support)
 *
 * All camera screens use the redesigned CameraScreen component.
 * Light/Dark mode toggle with NHAI DataLake design alignment.
 */

import { StatusBar } from 'expo-status-bar';
import React, { useState, useEffect, useCallback, useRef, createContext, useContext } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  SafeAreaView,
  Dimensions,
  ScrollView,
  Alert,
  TextInput,
  Modal,
  FlatList,
  KeyboardAvoidingView,
  Platform,
  Animated,
  StatusBar as RNStatusBar,
  Easing,
} from 'react-native';
import { CameraScreen } from './src/components/CameraScreen';
import {
  getRegisteredUsers,
  getAllAttendance,
  getPendingSync,
  logAttendance,
  deleteEmbedding,
  purgeSynced,
  clearAllData,
  BiometricRecord,
  AttendanceRecord,
} from './src/services/BiometricStore';
import { getAttendanceLocation } from './src/services/LocationService';
import { AdminPinGate } from './src/components/AdminPinGate';
import { exportAttendanceCsv, exportTodayAttendanceCsv } from './src/services/CsvExportService';

// Bundled model metrics (generated by scripts/train_face_model.py)
const MODEL_METRICS = require('./assets/models/model_metrics.json');

type Screen = 'onboarding' | 'home' | 'register' | 'authenticate' | 'attendance' | 'users' | 'help';

const { width: SCREEN_W, height: SCREEN_H } = Dimensions.get('window');

// ─── Theme Palettes ───────────────────────────────────────────────────────────
const LightTheme = {
  bg: '#F0F4F8',
  surface: '#FFFFFF',
  surfaceEl: '#F7F9FC',
  border: '#E2E8F0',
  accent: '#1B4F8A',        // NHAI Navy Blue
  accentDark: '#0F3460',
  accentLight: '#3B82F6',
  success: '#16A34A',
  warning: '#D97706',
  danger: '#DC2626',
  textPrimary: '#0F172A',
  textSecondary: '#475569',
  textMuted: '#94A3B8',
  cardShadow: 'rgba(15,23,42,0.08)',
  statusBarStyle: 'dark' as const,
  isDark: false,
};

const DarkTheme = {
  bg: '#080E1C',
  surface: '#111827',
  surfaceEl: '#1A2540',
  border: '#1E2D4A',
  accent: '#38BDF8',
  accentDark: '#0EA5E9',
  accentLight: '#7DD3FC',
  success: '#22C55E',
  warning: '#F59E0B',
  danger: '#EF4444',
  textPrimary: '#F1F5F9',
  textSecondary: '#94A3B8',
  textMuted: '#475569',
  cardShadow: 'rgba(0,0,0,0.3)',
  statusBarStyle: 'light' as const,
  isDark: true,
};

type Theme = typeof LightTheme;
const ThemeContext = createContext<{ theme: Theme; toggleTheme: () => void }>({
  theme: LightTheme,
  toggleTheme: () => { },
});
const useTheme = () => useContext(ThemeContext);

export default function App() {
  const [isDark, setIsDark] = useState(true);
  const theme = isDark ? DarkTheme : LightTheme;
  const toggleTheme = useCallback(() => setIsDark(prev => !prev), []);

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <AppContent />
    </ThemeContext.Provider>
  );
}

function AppContent() {
  const { theme, toggleTheme } = useTheme();
  const [screen, setScreen] = useState<Screen>('onboarding');
  const [users, setUsers] = useState<BiometricRecord[]>([]);
  const [attendance, setAttendance] = useState<AttendanceRecord[]>([]);
  const [pendingCount, setPendingCount] = useState(0);
  const [isSyncing, setIsSyncing] = useState(false);

  // Live inference metrics
  const [lastInferenceMs, setLastInferenceMs] = useState<number | null>(null);

  // ── Admin PIN Gate ────────────────────────────────────────────────────────
  const [pinGateVisible, setPinGateVisible] = useState(false);
  // The action to fire after PIN is verified
  const pendingActionRef = useRef<(() => void) | null>(null);

  /** Wrap any admin action behind the PIN gate */
  const requirePin = useCallback((action: () => void) => {
    pendingActionRef.current = action;
    setPinGateVisible(true);
  }, []);

  const handlePinSuccess = useCallback(() => {
    setPinGateVisible(false);
    pendingActionRef.current?.();
    pendingActionRef.current = null;
  }, []);

  const handlePinCancel = useCallback(() => {
    setPinGateVisible(false);
    pendingActionRef.current = null;
  }, []);

  // ── CSV Export ────────────────────────────────────────────────────────────
  const [isExporting, setIsExporting] = useState(false);

  const handleExportCsv = useCallback(async () => {
    if (isExporting) return;
    setIsExporting(true);
    try {
      const result = await exportAttendanceCsv(attendance);
      if (!result.success) {
        Alert.alert('Export Failed', result.message);
      }
    } finally {
      setIsExporting(false);
    }
  }, [attendance, isExporting]);

  // Registration modal inputs
  const [showRegModal, setShowRegModal] = useState(false);
  const [newUserName, setNewUserName] = useState('');
  const [newUserId, setNewUserId] = useState('');

  // Last auth result card
  const [lastAuthResult, setLastAuthResult] = useState<null | {
    name: string;
    sim: number;
    time: string;
    location: string;
  }>(null);

  const refreshData = useCallback(async () => {
    const [u, a, p] = await Promise.all([
      getRegisteredUsers(),
      getAllAttendance(),
      getPendingSync(),
    ]);
    setUsers(u);
    setAttendance(a.reverse());
    setPendingCount(p.length);
  }, []);

  useEffect(() => {
    if (screen !== 'onboarding') refreshData();
  }, [screen]);

  // ── Registration result ────────────────────────────────────────────────────
  const handleRegistrationResult = async (
    success: boolean,
    userId: string,
    name: string
  ) => {
    setScreen('home');
    if (success) {
      await refreshData();
      Alert.alert('✅ Registered!', `${name} has been enrolled successfully.`);
    }
  };

  // ── Authentication result ──────────────────────────────────────────────────
  const handleAuthResult = async (
    success: boolean,
    userId: string,
    name: string,
    similarity: number
  ) => {
    setScreen('home');
    if (success) {
      const locResult = await getAttendanceLocation();
      await logAttendance(userId, name, locResult.location, locResult.lat, locResult.lng);
      setLastAuthResult({
        name,
        sim: similarity,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        location: locResult.location,
      });
      await refreshData();
      Alert.alert(
        '✅ Authenticated!',
        `Welcome ${name}!\nMatch: ${(similarity * 100).toFixed(1)}%\n📍 ${locResult.location}\nAttendance logged.`
      );
    } else {
      Alert.alert(
        '❌ Not Recognized',
        'Face could not be matched. Please register first or try again.'
      );
    }
  };

  // ── Sync & Purge ───────────────────────────────────────────────────────────
  const handleSyncAndPurge = async () => {
    const pending = await getPendingSync();
    if (pending.length === 0) {
      Alert.alert('📡 Nothing to Sync', 'All attendance records are already synced.');
      return;
    }
    setIsSyncing(true);
    setTimeout(async () => {
      const purged = await purgeSynced();
      await refreshData();
      setIsSyncing(false);
      Alert.alert('✅ Sync Complete', `${purged} record(s) uploaded & purged from device.`);
    }, 1800);
  };

  // ═══════════════════════════════════════════════════════════════════════════
  //  ONBOARDING SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'onboarding') {
    return <OnboardingScreen onFinish={() => setScreen('home')} />;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  CAMERA SCREENS
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'register') {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar style="light" />
        <CameraScreen
          mode="register"
          userId={newUserId.trim() || `emp_${Date.now()}`}
          userName={newUserName.trim() || 'Field Personnel'}
          onRegistrationResult={handleRegistrationResult}
          onAuthenticationResult={() => { }}
          onInferenceTime={setLastInferenceMs}
        />
        <TouchableOpacity
          style={s.floatingCancel}
          onPress={() => setScreen('home')}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Text style={s.floatingCancelText}>✕</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (screen === 'authenticate') {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar style="light" />
        <CameraScreen
          mode="authenticate"
          onAuthenticationResult={handleAuthResult}
          onRegistrationResult={() => { }}
          onInferenceTime={setLastInferenceMs}
        />
        <TouchableOpacity
          style={s.floatingCancel}
          onPress={() => setScreen('home')}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Text style={s.floatingCancelText}>✕</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  HELP SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'help') {
    return <HelpScreen onBack={() => setScreen('home')} />;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  ATTENDANCE LOG
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'attendance') {
    const todayStr = new Date().toLocaleDateString();
    const todayCount = attendance.filter(
      a => new Date(a.timestamp).toLocaleDateString() === todayStr
    ).length;

    return (
      <SafeAreaView style={[s.safeContainer, { backgroundColor: theme.bg }]}>
        <StatusBar style={theme.statusBarStyle} />
        <ScreenHeader
          title="Attendance Log"
          icon="📋"
          onBack={() => setScreen('home')}
          rightAction={
            {
              label: isExporting ? '…' : '⬇ CSV',
              onPress: handleExportCsv,
              color: theme.accent,
            }
          }
        />
        {/* Sync button below header when there are pending records */}
        {pendingCount > 0 && (
          <TouchableOpacity
            style={[s.syncStrip, { backgroundColor: theme.isDark ? 'rgba(245,158,11,0.1)' : 'rgba(217,119,6,0.07)', borderColor: theme.warning }]}
            onPress={handleSyncAndPurge}
            activeOpacity={0.75}
          >
            <Text style={[s.syncStripText, { color: theme.warning }]}>
              {isSyncing ? '🔄 Syncing…' : `📡 ${pendingCount} record(s) pending sync — Tap to upload`}
            </Text>
          </TouchableOpacity>
        )}
        {/* Summary strip */}
        <View style={[s.summaryStrip, { backgroundColor: theme.surface, borderColor: theme.border }]}>
          <View style={s.summaryItem}>
            <Text style={[s.summaryNumber, { color: theme.textPrimary }]}>{attendance.length}</Text>
            <Text style={[s.summaryLabel, { color: theme.textMuted }]}>Total</Text>
          </View>
          <View style={[s.summaryDivider, { backgroundColor: theme.border }]} />
          <View style={s.summaryItem}>
            <Text style={[s.summaryNumber, { color: theme.accent }]}>{todayCount}</Text>
            <Text style={[s.summaryLabel, { color: theme.textMuted }]}>Today</Text>
          </View>
          <View style={[s.summaryDivider, { backgroundColor: theme.border }]} />
          <View style={s.summaryItem}>
            <Text style={[s.summaryNumber, { color: pendingCount > 0 ? theme.warning : theme.success }]}>
              {pendingCount}
            </Text>
            <Text style={[s.summaryLabel, { color: theme.textMuted }]}>Pending</Text>
          </View>
        </View>

        {attendance.length === 0 ? (
          <EmptyState icon="📋" title="No records yet" subtitle="Authenticate a face to log attendance" />
        ) : (
          <FlatList
            data={attendance}
            keyExtractor={item => item.id}
            contentContainerStyle={s.listContent}
            renderItem={({ item }) => (
              <View
                style={[
                  s.logCard,
                  {
                    backgroundColor: item.synced ? (theme.isDark ? 'rgba(34,197,94,0.06)' : 'rgba(22,163,74,0.04)') : theme.surface,
                    borderColor: item.synced ? (theme.isDark ? 'rgba(34,197,94,0.25)' : 'rgba(22,163,74,0.2)') : theme.warning,
                  },
                ]}
              >
                <View style={[s.logCardAvatar, { backgroundColor: theme.accent }]}>
                  <Text style={s.logCardAvatarText}>{item.name[0]?.toUpperCase() ?? '?'}</Text>
                </View>
                <View style={s.logCardBody}>
                  <Text style={[s.logName, { color: theme.textPrimary }]}>{item.name}</Text>
                  <Text style={[s.logId, { color: theme.textMuted }]}>ID: {item.userId}</Text>
                  <Text style={[s.logLocation, { color: theme.textSecondary }]}>📍 {item.location}</Text>
                </View>
                <View style={s.logCardRight}>
                  <Text style={[s.logTime, { color: theme.textPrimary }]}>
                    {new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </Text>
                  <Text style={[s.logDate, { color: theme.textMuted }]}>
                    {new Date(item.timestamp).toLocaleDateString()}
                  </Text>
                  <View style={[s.syncBadge, { backgroundColor: item.synced ? theme.success : theme.warning }]}>
                    <Text style={s.syncBadgeText}>{item.synced ? '✓ Synced' : '⏳ Pending'}</Text>
                  </View>
                </View>
              </View>
            )}
          />
        )}
      </SafeAreaView>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  REGISTERED USERS
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'users') {
    return (
      <SafeAreaView style={[s.safeContainer, { backgroundColor: theme.bg }]}>
        <StatusBar style={theme.statusBarStyle} />
        <ScreenHeader title="Enrolled Users" icon="👥" onBack={() => setScreen('home')} />

        {users.length === 0 ? (
          <EmptyState icon="👤" title="No users enrolled" subtitle="Register a face from the home screen" />
        ) : (
          <FlatList
            data={users}
            keyExtractor={item => item.userId}
            contentContainerStyle={s.listContent}
            renderItem={({ item }) => (
              <View style={[s.userCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                <View style={[s.userAvatar, { backgroundColor: theme.accent }]}>
                  <Text style={s.userAvatarText}>{item.name[0]?.toUpperCase() ?? '?'}</Text>
                </View>
                <View style={s.userInfo}>
                  <Text style={[s.userName, { color: theme.textPrimary }]}>{item.name}</Text>
                  <Text style={[s.userId, { color: theme.textMuted }]}>🪪 {item.userId}</Text>
                  <Text style={[s.userDate, { color: theme.textMuted }]}>
                    Enrolled {new Date(item.registeredAt).toLocaleDateString()}
                  </Text>
                </View>
                <TouchableOpacity
                  style={s.deleteBtn}
                  onPress={() =>
                    Alert.alert('Remove User?', `Delete ${item.name}'s biometric record?`, [
                      { text: 'Cancel', style: 'cancel' },
                      {
                        text: 'Delete',
                        style: 'destructive',
                        onPress: async () => {
                          await deleteEmbedding(item.userId);
                          refreshData();
                        },
                      },
                    ])
                  }
                  hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                >
                  <Text style={s.deleteBtnText}>🗑</Text>
                </TouchableOpacity>
              </View>
            )}
          />
        )}

        {users.length > 0 && (
          <View style={s.dangerZone}>
            <TouchableOpacity
              style={s.dangerBtn}
              onPress={() =>
                Alert.alert(
                  '⚠️ Clear All Data?',
                  'This will permanently remove all enrolled faces and attendance records.',
                  [
                    { text: 'Cancel', style: 'cancel' },
                    {
                      text: 'Clear Everything',
                      style: 'destructive',
                      onPress: async () => {
                        await clearAllData();
                        await refreshData();
                        setLastAuthResult(null);
                        Alert.alert('🗑 Cleared', 'All local data has been removed.');
                      },
                    },
                  ]
                )
              }
            >
              <Text style={s.dangerBtnText}>🗑 Clear All Data</Text>
            </TouchableOpacity>
          </View>
        )}
      </SafeAreaView>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  HOME SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  return (
    <SafeAreaView style={[s.safeContainer, { backgroundColor: theme.bg }]}>
      <StatusBar style={theme.statusBarStyle} />
      <ScrollView
        contentContainerStyle={s.homeScroll}
        showsVerticalScrollIndicator={false}
      >
        {/* ── NHAI Header ── */}
        <View style={s.homeHeader}>
          <View style={s.headerTopRow}>
            <View style={{ flex: 1 }} />
            {/* Theme Toggle */}
            <TouchableOpacity
              style={[s.themeToggle, { backgroundColor: theme.surface, borderColor: theme.border }]}
              onPress={toggleTheme}
              activeOpacity={0.7}
            >
              <Text style={s.themeToggleIcon}>{theme.isDark ? '☀️' : '🌙'}</Text>
            </TouchableOpacity>
          </View>

          <View style={s.badgeRow}>
            <View style={[s.badge, { backgroundColor: theme.isDark ? 'rgba(56,189,248,0.12)' : 'rgba(27,79,138,0.08)', borderColor: theme.isDark ? 'rgba(56,189,248,0.25)' : 'rgba(27,79,138,0.2)' }]}>
              <Text style={[s.badgeText, { color: theme.accent }]}>NHAI · DATALAKE 3.0</Text>
            </View>
            <View style={[s.badge, { backgroundColor: theme.isDark ? 'rgba(34,197,94,0.1)' : 'rgba(22,163,74,0.06)', borderColor: theme.isDark ? 'rgba(34,197,94,0.25)' : 'rgba(22,163,74,0.15)' }]}>
              <Text style={[s.badgeText, { color: theme.success }]}>⚡ OFFLINE</Text>
            </View>
          </View>
          <Text style={[s.homeTitle, { color: theme.textPrimary }]}>Secure Offline{'\n'}Biometric System</Text>
          <Text style={[s.homeSubtitle, { color: theme.textMuted }]}>
            AI-powered facial recognition · No internet required
          </Text>
        </View>

        {/* ── Stats Row ── */}
        <View style={s.statsRow}>
          <StatCard number={users.length} label="Enrolled" icon="👤" onPress={() => setScreen('users')} />
          <StatCard number={attendance.length} label="Records" icon="📋" onPress={() => setScreen('attendance')} />
          <StatCard number={pendingCount} label="Pending" icon="📡" highlight={pendingCount > 0} onPress={handleSyncAndPurge} />
        </View>

        {/* ── Last Auth Result Card ── */}
        {lastAuthResult && (
          <View style={[s.authResultCard, { backgroundColor: theme.isDark ? 'rgba(34,197,94,0.08)' : 'rgba(22,163,74,0.05)', borderColor: theme.isDark ? 'rgba(34,197,94,0.3)' : 'rgba(22,163,74,0.2)' }]}>
            <View style={s.authResultHeader}>
              <Text style={[s.authResultBadge, { color: theme.success }]}>LAST AUTHENTICATION</Text>
              <Text style={[s.authResultMatch, { color: theme.success }]}>
                {(lastAuthResult.sim * 100).toFixed(1)}% match
              </Text>
            </View>
            <Text style={[s.authResultName, { color: theme.textPrimary }]}>{lastAuthResult.name}</Text>
            <Text style={[s.authResultMeta, { color: theme.textSecondary }]}>
              🕐 {lastAuthResult.time}  ·  📍 {lastAuthResult.location}
            </Text>
          </View>
        )}

        {/* ── Primary Action — Authenticate ── */}
        <TouchableOpacity
          style={[s.primaryBtn, { backgroundColor: theme.accentDark }]}
          onPress={() => setScreen('authenticate')}
          activeOpacity={0.85}
        >
          <View style={s.primaryBtnInner}>
            <View style={s.primaryBtnIconWrap}>
              <Text style={s.primaryBtnIcon}>🔒</Text>
            </View>
            <View style={s.primaryBtnTextWrap}>
              <Text style={s.primaryBtnTitle}>Authenticate Face</Text>
              <Text style={s.primaryBtnSub}>Verify identity & log attendance</Text>
            </View>
            <Text style={s.primaryBtnArrow}>›</Text>
          </View>
        </TouchableOpacity>

        {/* ── Register Button — PIN protected ── */}
        <TouchableOpacity
          style={[s.secondaryBtn, { backgroundColor: theme.surface, borderColor: theme.border }]}
          onPress={() => requirePin(() => setShowRegModal(true))}
          activeOpacity={0.85}
        >
          <Text style={s.secondaryBtnIcon}>➕</Text>
          <Text style={[s.secondaryBtnText, { color: theme.textSecondary }]}>Enroll New Face</Text>
          <Text style={{ fontSize: 12, color: theme.textMuted, marginLeft: 4 }}>🔑</Text>
        </TouchableOpacity>

        {/* ── Quick Nav Grid ── */}
        <View style={s.navGrid}>
          <NavCard icon="📋" title="Attendance" subtitle={`${attendance.length} records`} onPress={() => setScreen('attendance')} />
          <NavCard icon="👥" title="Users" subtitle={`${users.length} enrolled`} onPress={() => requirePin(() => setScreen('users'))} />
          <NavCard icon="❓" title="Help" subtitle="Get support" onPress={() => setScreen('help')} />
        </View>

        {/* ── How to Use ── */}
        <View style={[s.modelCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
          <View style={s.modelCardHeader}>
            <Text style={[s.modelCardTitle, { color: theme.textPrimary }]}>📖 How to Use</Text>
          </View>
          <Text style={[s.integrationStepText, { color: theme.textSecondary, marginBottom: 8 }]}>
            <Text style={{ fontWeight: 'bold' }}>Authentication & Registration:</Text> Keep your face at the center of the frame.
          </Text>
          <Text style={[s.integrationStepText, { color: theme.textSecondary, marginBottom: 8 }]}>
            You will be asked to <Text style={{ fontWeight: 'bold', color: theme.accent }}>Blink</Text>, <Text style={{ fontWeight: 'bold', color: theme.accent }}>Smile</Text>, and <Text style={{ fontWeight: 'bold', color: theme.accent }}>Rotate your head</Text>.
          </Text>
          <Text style={[s.integrationStepText, { color: theme.textSecondary }]}>
            These measures ensure there is no sort of cheating (like using a photo or video). We use math and AI models to detect liveness accurately.
          </Text>
        </View>

        {/* ── Security & Compliance Card ── */}
        <View style={[s.modelCard, { backgroundColor: theme.isDark ? 'rgba(15,22,42,0.95)' : '#FFFFFF', borderColor: theme.isDark ? 'rgba(34,197,94,0.25)' : 'rgba(22,163,74,0.15)' }]}>
          <View style={s.modelCardHeader}>
            <Text style={[s.modelCardTitle, { color: theme.textPrimary }]}>🔐 Security & Compliance</Text>
            <View style={[s.modelBadge, { backgroundColor: theme.isDark ? 'rgba(34,197,94,0.15)' : 'rgba(22,163,74,0.06)', borderColor: theme.isDark ? 'rgba(34,197,94,0.3)' : 'rgba(22,163,74,0.12)' }]}>
              <Text style={[s.modelBadgeText, { color: theme.success }]}>SECURE</Text>
            </View>
          </View>

          <View style={s.securityGrid}>
            <View style={[s.securityItem, { backgroundColor: theme.surfaceEl, borderColor: theme.border }]}>
              <Text style={s.securityIcon}>🔒</Text>
              <Text style={[s.securityTitle, { color: theme.textPrimary }]}>AES-256</Text>
              <Text style={[s.securityDesc, { color: theme.textMuted }]}>Encrypted at rest</Text>
            </View>
            <View style={[s.securityItem, { backgroundColor: theme.surfaceEl, borderColor: theme.border }]}>
              <Text style={s.securityIcon}>📵</Text>
              <Text style={[s.securityTitle, { color: theme.textPrimary }]}>Zero Cloud</Text>
              <Text style={[s.securityDesc, { color: theme.textMuted }]}>On-device only</Text>
            </View>
            <View style={[s.securityItem, { backgroundColor: theme.surfaceEl, borderColor: theme.border }]}>
              <Text style={s.securityIcon}>🗑️</Text>
              <Text style={[s.securityTitle, { color: theme.textPrimary }]}>Crypto Wipe</Text>
              <Text style={[s.securityDesc, { color: theme.textMuted }]}>Zeroed on purge</Text>
            </View>
            <View style={[s.securityItem, { backgroundColor: theme.surfaceEl, borderColor: theme.border }]}>
              <Text style={s.securityIcon}>📱</Text>
              <Text style={[s.securityTitle, { color: theme.textPrimary }]}>Android 8+</Text>
              <Text style={[s.securityDesc, { color: theme.textMuted }]}>3GB RAM min</Text>
            </View>
          </View>
        </View>

        {/* ── Model Stats Card ── */}
        <View style={[s.modelCard, { backgroundColor: theme.isDark ? 'rgba(15,22,42,0.95)' : '#FFFFFF', borderColor: theme.isDark ? 'rgba(56,189,248,0.25)' : theme.border }]}>
          <View style={s.modelCardHeader}>
            <Text style={[s.modelCardTitle, { color: theme.textPrimary }]}>🧠 AI Pipeline Performance</Text>
            <View style={[s.modelBadge, { backgroundColor: theme.isDark ? 'rgba(56,189,248,0.15)' : 'rgba(27,79,138,0.08)', borderColor: theme.isDark ? 'rgba(56,189,248,0.3)' : 'rgba(27,79,138,0.15)' }]}>
              <Text style={[s.modelBadgeText, { color: theme.accent }]}>EDGE AI · C++</Text>
            </View>
          </View>
          <Text style={[s.modelName, { color: theme.accent }]}>{MODEL_METRICS.modelName}</Text>
          <Text style={[s.modelDataset, { color: theme.textMuted }]}>📊 {MODEL_METRICS.trainingDataset} · {MODEL_METRICS.trainingPairs.toLocaleString()} pairs</Text>

          <View style={s.modelMetricsGrid}>
            <MetricCell label="Accuracy" value={`${MODEL_METRICS.verificationAccuracy}%`} color={theme.success} />
            <MetricCell label="AUC" value={MODEL_METRICS.auc.toFixed(3)} color={theme.accentLight} />
            <MetricCell label="TAR@FAR" value={`${MODEL_METRICS.tarAtFar01}%`} color="#A78BFA" />
            <MetricCell
              label="Inference"
              value={lastInferenceMs !== null ? `${lastInferenceMs}ms` : `~${MODEL_METRICS.avgInferenceMs}ms`}
              color={theme.warning}
            />
            <MetricCell label="Size" value={`${MODEL_METRICS.modelSizeMb} MB`} color={theme.textSecondary} />
            <MetricCell label="Embed" value={`${MODEL_METRICS.embeddingDim}-D`} color={theme.textSecondary} />
          </View>
        </View>

        {/* ── Footer Info ── */}
        <View style={[s.footerCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
          <Text style={[s.footerTitle, { color: theme.textSecondary }]}>NHAI Hackathon 7.0</Text>
          <Text style={[s.footerSub, { color: theme.textMuted }]}>Edge AI · C++ TFLite Pipeline · Cosine Similarity</Text>
          <Text style={[s.footerSub, { color: theme.textMuted }]}>EAR/MAR/PnP Liveness · Offline-First · Auto Sync & Purge</Text>
          <Text style={[s.footerSub, { color: theme.textMuted }]}>Android 8.0+ · No cloud dependency</Text>
        </View>
      </ScrollView>

      {/* ── Registration Modal ── */}
      <Modal visible={showRegModal} transparent animationType="slide" statusBarTranslucent>
        <KeyboardAvoidingView
          style={s.modalKAV}
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        >
          <TouchableOpacity
            style={s.modalScrim}
            activeOpacity={1}
            onPress={() => setShowRegModal(false)}
          />
          <View style={[s.modalSheet, { backgroundColor: theme.surface, borderTopColor: theme.border }]}>
            <View style={[s.modalHandle, { backgroundColor: theme.border }]} />
            <Text style={[s.modalTitle, { color: theme.textPrimary }]}>Enroll New Face</Text>

            <Text style={[s.modalLabel, { color: theme.textSecondary }]}>Full Name *</Text>
            <TextInput
              id="reg-name-input"
              style={[s.modalInput, { backgroundColor: theme.bg, color: theme.textPrimary, borderColor: theme.border }]}
              placeholder="e.g. Rahul Sharma"
              placeholderTextColor={theme.textMuted}
              value={newUserName}
              onChangeText={setNewUserName}
              returnKeyType="next"
              autoCapitalize="words"
            />

            <Text style={[s.modalLabel, { color: theme.textSecondary }]}>Employee / User ID</Text>
            <TextInput
              id="reg-id-input"
              style={[s.modalInput, { backgroundColor: theme.bg, color: theme.textPrimary, borderColor: theme.border }]}
              placeholder="e.g. EMP-001 (auto-generated if blank)"
              placeholderTextColor={theme.textMuted}
              value={newUserId}
              onChangeText={setNewUserId}
              returnKeyType="done"
              autoCapitalize="characters"
            />

            <TouchableOpacity
              id="reg-start-btn"
              style={[s.modalBtn, { backgroundColor: theme.accentDark }, !newUserName.trim() && s.modalBtnDisabled]}
              disabled={!newUserName.trim()}
              onPress={() => {
                setShowRegModal(false);
                setScreen('register');
              }}
              activeOpacity={0.85}
            >
              <Text style={s.modalBtnText}>📷  Start Registration</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={s.modalCancelBtn}
              onPress={() => {
                setShowRegModal(false);
                setNewUserName('');
                setNewUserId('');
              }}
            >
              <Text style={[s.modalCancelText, { color: theme.textMuted }]}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </KeyboardAvoidingView>
      </Modal>

      {/* ── Admin PIN Gate ── */}
      <AdminPinGate
        visible={pinGateVisible}
        onSuccess={handlePinSuccess}
        onCancel={handlePinCancel}
        accentColor={theme.accent}
        bgColor={theme.surface}
        textColor={theme.textPrimary}
      />
    </SafeAreaView>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
//  ONBOARDING SCREEN (Swipeable slider)
// ═══════════════════════════════════════════════════════════════════════════════

const ONBOARDING_SLIDES = [
  {
    icon: '🛣️',
    badge: 'NHAI · DATALAKE 3.0',
    title: 'Digital Backbone for\nNational Highways',
    subtitle: 'Secure, offline biometric attendance\npowered by edge AI',
    gradient: ['#0F3460', '#1B4F8A'],
  },
  {
    icon: '🔒',
    badge: 'EDGE AI',
    title: 'Face Authentication\nOn-Device',
    subtitle: 'No internet needed. TFLite C++ pipeline\nruns entirely on your phone',
    gradient: ['#0F3460', '#1B6B93'],
  },
  {
    icon: '👁️',
    badge: 'ANTI-SPOOFING',
    title: 'Liveness Detection\nBuilt-In',
    subtitle: 'EAR blink detection, MAR smile check,\nand PnP head-pose verification',
    gradient: ['#0F3460', '#2E4057'],
  },
  {
    icon: '📡',
    badge: 'OFFLINE-FIRST',
    title: 'Sync When\nConnected',
    subtitle: 'All data stored locally.\nAuto-sync & purge when network available',
    gradient: ['#0F3460', '#1A3C6E'],
  },
];

function OnboardingScreen({ onFinish }: { onFinish: () => void }) {
  const [activeIdx, setActiveIdx] = useState(0);
  const scrollRef = useRef<ScrollView>(null);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const scaleAnim = useRef(new Animated.Value(0.9)).current;

  useEffect(() => {
    Animated.parallel([
      Animated.timing(fadeAnim, { toValue: 1, duration: 600, useNativeDriver: true }),
      Animated.spring(scaleAnim, { toValue: 1, useNativeDriver: true, damping: 15 }),
    ]).start();
  }, [activeIdx]);

  const goToSlide = (idx: number) => {
    scrollRef.current?.scrollTo({ x: idx * SCREEN_W, animated: true });
    fadeAnim.setValue(0);
    scaleAnim.setValue(0.9);
    setActiveIdx(idx);
  };

  const handleScroll = (e: any) => {
    const x = e.nativeEvent.contentOffset.x;
    const idx = Math.round(x / SCREEN_W);
    if (idx !== activeIdx) {
      fadeAnim.setValue(0);
      scaleAnim.setValue(0.9);
      setActiveIdx(idx);
    }
  };

  const isLast = activeIdx === ONBOARDING_SLIDES.length - 1;

  return (
    <View style={ob.container}>
      <StatusBar style="light" />
      <ScrollView
        ref={scrollRef}
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={false}
        onMomentumScrollEnd={handleScroll}
        scrollEventThrottle={16}
      >
        {ONBOARDING_SLIDES.map((slide, i) => (
          <View key={i} style={[ob.slide, { width: SCREEN_W }]}>
            <View style={ob.slideContent}>
              <Animated.View style={[ob.iconContainer, { opacity: fadeAnim, transform: [{ scale: scaleAnim }] }]}>
                <Text style={ob.icon}>{slide.icon}</Text>
              </Animated.View>
              <View style={[ob.badgeWrap]}>
                <Text style={ob.badgeLabel}>{slide.badge}</Text>
              </View>
              <Animated.Text style={[ob.title, { opacity: fadeAnim }]}>
                {slide.title}
              </Animated.Text>
              <Animated.Text style={[ob.subtitle, { opacity: fadeAnim }]}>
                {slide.subtitle}
              </Animated.Text>
            </View>
          </View>
        ))}
      </ScrollView>

      {/* Dots + button at bottom */}
      <View style={ob.bottomSection}>
        <View style={ob.dots}>
          {ONBOARDING_SLIDES.map((_, i) => (
            <View
              key={i}
              style={[
                ob.dot,
                i === activeIdx ? ob.dotActive : ob.dotInactive,
              ]}
            />
          ))}
        </View>

        <TouchableOpacity
          style={ob.nextBtn}
          onPress={() => {
            if (isLast) {
              onFinish();
            } else {
              goToSlide(activeIdx + 1);
            }
          }}
          activeOpacity={0.85}
        >
          <Text style={ob.nextBtnText}>{isLast ? 'Get Started' : 'Next'}</Text>
          <Text style={ob.nextBtnArrow}>{isLast ? '→' : '›'}</Text>
        </TouchableOpacity>

        {!isLast && (
          <TouchableOpacity style={ob.skipBtn} onPress={onFinish}>
            <Text style={ob.skipText}>Skip</Text>
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
}

const ob = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1120',
  },
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideContent: {
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  iconContainer: {
    width: 120,
    height: 120,
    borderRadius: 36,
    backgroundColor: 'rgba(56,189,248,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
    borderWidth: 2,
    borderColor: 'rgba(56,189,248,0.2)',
  },
  icon: {
    fontSize: 56,
  },
  badgeWrap: {
    backgroundColor: 'rgba(27,79,138,0.3)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(56,189,248,0.25)',
  },
  badgeLabel: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#F1F5F9',
    textAlign: 'center',
    lineHeight: 40,
    letterSpacing: -0.5,
    marginBottom: 14,
  },
  subtitle: {
    fontSize: 15,
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 22,
  },
  bottomSection: {
    paddingHorizontal: 32,
    paddingBottom: Platform.OS === 'ios' ? 50 : 36,
    alignItems: 'center',
  },
  dots: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 28,
  },
  dot: {
    height: 8,
    borderRadius: 4,
  },
  dotActive: {
    width: 28,
    backgroundColor: '#38BDF8',
  },
  dotInactive: {
    width: 8,
    backgroundColor: 'rgba(148,163,184,0.3)',
  },
  nextBtn: {
    flexDirection: 'row',
    backgroundColor: '#1B4F8A',
    borderRadius: 16,
    paddingVertical: 17,
    paddingHorizontal: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    elevation: 6,
    shadowColor: '#1B4F8A',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  nextBtnText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '700',
  },
  nextBtnArrow: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 22,
    fontWeight: '300',
  },
  skipBtn: {
    marginTop: 16,
    padding: 10,
  },
  skipText: {
    color: '#64748B',
    fontSize: 15,
    fontWeight: '600',
  },
});

// ═══════════════════════════════════════════════════════════════════════════════
//  HELP SCREEN
// ═══════════════════════════════════════════════════════════════════════════════

const HELP_TOPICS = [
  { 
    icon: '🔒', 
    title: 'Face Authentication', 
    desc: 'Verify your identity securely using a live face scan. Center your face within the frame and follow the prompts to complete the validation sequence.' 
  },
  { 
    icon: '📝', 
    title: 'Registration', 
    desc: 'Enroll your biometric profile for the first time. Enter your Employee ID, align your face in the marker, and perform the baseline initialization actions.' 
  },
  { 
    icon: '📋', 
    title: 'Attendance', 
    desc: 'View, track, and manage your localized daily attendance records, validation states, and offline logs.' 
  },
  { 
    icon: '👁️', 
    title: 'Liveness Check (Anti-Cheating)', 
    desc: 'To ensure no cheating occurs, our AI uses advanced math to detect if a live human is present. You will be asked to:\n1. Blink\n2. Smile\n3. Rotate Head\nThis ensures photos or videos cannot fool the system.' 
  },
  { 
    icon: '📡', 
    title: 'Sync & Offline', 
    desc: 'Enables seamless zero-network operation. Logs are cached locally in an encrypted state and automatically synchronized to the server once connectivity is restored, followed by an immediate local purge.' 
  },
  { 
    icon: '🔐', 
    title: 'Data Privacy', 
    desc: 'Enterprise-grade security architecture. Biometric templates are instantly converted into encrypted mathematical embeddings isolated completely from external applications.' 
  },
];

function HelpScreen({ onBack }: { onBack: () => void }) {
  const { theme } = useTheme();

  return (
    <SafeAreaView style={[s.safeContainer, { backgroundColor: theme.bg }]}>
      <StatusBar style={theme.statusBarStyle} />
      <ScreenHeader title="Help & Support" icon="❓" onBack={onBack} />

      <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }} showsVerticalScrollIndicator={false}>
        {/* Search bar (visual only — demo) */}
        <View style={[helpS.searchBar, { backgroundColor: theme.surface, borderColor: theme.border }]}>
          <Text style={[helpS.searchIcon, { color: theme.textMuted }]}>🔍</Text>
          <Text style={[helpS.searchPlaceholder, { color: theme.textMuted }]}>Search help topics</Text>
        </View>

        <Text style={[helpS.sectionTitle, { color: theme.textPrimary }]}>Help Topics</Text>

        {HELP_TOPICS.map((topic, i) => (
          <TouchableOpacity
            key={i}
            style={[helpS.topicCard, { backgroundColor: theme.surface, borderColor: theme.border }]}
            activeOpacity={0.7}
            onPress={() => Alert.alert(topic.title, topic.desc)}
          >
            <View style={[helpS.topicIcon, { backgroundColor: theme.isDark ? 'rgba(56,189,248,0.1)' : 'rgba(27,79,138,0.06)' }]}>
              <Text style={{ fontSize: 22 }}>{topic.icon}</Text>
            </View>
            <View style={{ flex: 1, justifyContent: 'center' }}>
              <Text style={[helpS.topicTitle, { color: theme.textPrimary }]}>{topic.title}</Text>
            </View>
            <Text style={[helpS.topicArrow, { color: theme.textMuted }]}>›</Text>
          </TouchableOpacity>
        ))}

        {/* Quick actions */}
        <View style={helpS.quickRow}>
          <TouchableOpacity
            style={[helpS.quickCard, { backgroundColor: theme.surface, borderColor: theme.border }]}
            activeOpacity={0.7}
            onPress={() => Alert.alert('Contact', 'support@nhai.gov.in')}
          >
            <Text style={helpS.quickIcon}>📧</Text>
            <Text style={[helpS.quickLabel, { color: theme.textPrimary }]}>Mail us</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[helpS.quickCard, { backgroundColor: theme.surface, borderColor: theme.border }]}
            activeOpacity={0.7}
            onPress={() => Alert.alert('Version', `NHAI Datalake 3.0\nEdge AI Biometric Module\nv1.0.0`)}
          >
            <Text style={helpS.quickIcon}>ℹ️</Text>
            <Text style={[helpS.quickLabel, { color: theme.textPrimary }]}>About</Text>
          </TouchableOpacity>
        </View>

        {/* Version info */}
        <View style={helpS.versionBox}>
          <Text style={[helpS.versionText, { color: theme.textMuted }]}>NHAI Datalake 3.0 — Edge AI Module</Text>
          <Text style={[helpS.versionText, { color: theme.textMuted }]}>Version 1.0.0 · Hackathon 7.0</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const helpS = StyleSheet.create({
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 24,
    borderWidth: 1,
    gap: 10,
  },
  searchIcon: { fontSize: 16 },
  searchPlaceholder: { fontSize: 15 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  topicCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    gap: 12,
  },
  topicIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topicTitle: { fontSize: 15, fontWeight: '700' },
  topicDesc: { fontSize: 12, marginTop: 2 },
  topicArrow: { fontSize: 22, fontWeight: '300' },
  quickRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  quickCard: {
    flex: 1,
    borderRadius: 14,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
    gap: 8,
  },
  quickIcon: { fontSize: 28 },
  quickLabel: { fontSize: 14, fontWeight: '700' },
  versionBox: {
    alignItems: 'center',
    marginTop: 28,
    gap: 4,
  },
  versionText: { fontSize: 12 },
});

// ─── Sub-Components ───────────────────────────────────────────────────────────

function ScreenHeader({
  title,
  icon,
  onBack,
  rightAction,
}: {
  title: string;
  icon?: string;
  onBack: () => void;
  rightAction?: { label: string; onPress: () => void; color?: string };
}) {
  const { theme } = useTheme();
  return (
    <View style={[s.screenHeader, { borderBottomColor: theme.border }]}>
      <TouchableOpacity onPress={onBack} style={s.headerBack} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
        <Text style={[s.headerBackText, { color: theme.accent }]}>← Back</Text>
      </TouchableOpacity>
      <Text style={[s.screenTitle, { color: theme.textPrimary }]}>{icon ? `${icon} ` : ''}{title}</Text>
      {rightAction ? (
        <TouchableOpacity
          style={[s.headerRight, { backgroundColor: rightAction.color ?? theme.accent }]}
          onPress={rightAction.onPress}
        >
          <Text style={s.headerRightText}>{rightAction.label}</Text>
        </TouchableOpacity>
      ) : (
        <View style={{ width: 72 }} />
      )}
    </View>
  );
}

function StatCard({
  number,
  label,
  icon,
  highlight = false,
  onPress,
}: {
  number: number;
  label: string;
  icon: string;
  highlight?: boolean;
  onPress?: () => void;
}) {
  const { theme } = useTheme();
  return (
    <TouchableOpacity
      style={[
        s.statCard,
        {
          backgroundColor: theme.surface,
          borderColor: highlight ? theme.warning : theme.border,
          shadowColor: theme.cardShadow,
        },
      ]}
      onPress={onPress}
      activeOpacity={0.75}
    >
      <Text style={s.statIcon}>{icon}</Text>
      <Text style={[s.statNumber, { color: highlight ? theme.warning : theme.textPrimary }]}>
        {number}
      </Text>
      <Text style={[s.statLabel, { color: theme.textMuted }]}>{label}</Text>
    </TouchableOpacity>
  );
}

function NavCard({
  icon,
  title,
  subtitle,
  highlight = false,
  onPress,
}: {
  icon: string;
  title: string;
  subtitle: string;
  highlight?: boolean;
  onPress: () => void;
}) {
  const { theme } = useTheme();
  return (
    <TouchableOpacity
      style={[
        s.navCard,
        {
          backgroundColor: theme.surface,
          borderColor: highlight ? 'rgba(245,158,11,0.5)' : theme.border,
        },
      ]}
      onPress={onPress}
      activeOpacity={0.75}
    >
      <Text style={s.navCardIcon}>{icon}</Text>
      <Text style={[s.navCardTitle, { color: theme.textPrimary }]}>{title}</Text>
      <Text style={[s.navCardSub, { color: highlight ? theme.warning : theme.textMuted }]}>
        {subtitle}
      </Text>
    </TouchableOpacity>
  );
}

function EmptyState({
  icon,
  title,
  subtitle,
}: {
  icon: string;
  title: string;
  subtitle: string;
}) {
  const { theme } = useTheme();
  return (
    <View style={s.emptyState}>
      <Text style={s.emptyIcon}>{icon}</Text>
      <Text style={[s.emptyTitle, { color: theme.textPrimary }]}>{title}</Text>
      <Text style={[s.emptySub, { color: theme.textMuted }]}>{subtitle}</Text>
    </View>
  );
}

function MetricCell({
  label,
  value,
  color,
}: {
  label: string;
  value: string;
  color: string;
}) {
  const { theme } = useTheme();
  return (
    <View style={[s.metricCell, { backgroundColor: theme.surfaceEl, borderColor: theme.border }]}>
      <Text style={[s.metricCellValue, { color }]}>{value}</Text>
      <Text style={[s.metricCellLabel, { color: theme.textMuted }]}>{label}</Text>
    </View>
  );
}

function PipelineStep({ label, sublabel, color, isFirst = false }: { label: string; sublabel: string; color: string; isFirst?: boolean }) {
  return (
    <View style={s.pipelineStep}>
      <View style={[s.pipelineDot, { backgroundColor: color }]} />
      <Text style={[s.pipelineLabel, { color }]}>{label}</Text>
      <Text style={[s.pipelineSublabel, { color: 'rgba(148,163,184,0.8)' }]}>{sublabel}</Text>
    </View>
  );
}

function PipelineArrow({ color }: { color: string }) {
  return <Text style={[s.pipelineArrowText, { color }]}>→</Text>;
}

function ChecklistItem({ label, checked, theme }: { label: string; checked: boolean; theme: Theme }) {
  return (
    <View style={s.checklistRow}>
      <View style={[s.checklistDot, { backgroundColor: checked ? theme.success : theme.textMuted }]}>
        <Text style={s.checklistCheck}>{checked ? '✓' : ' '}</Text>
      </View>
      <Text style={[s.checklistLabel, { color: theme.textPrimary }]}>{label}</Text>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  safeContainer: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? (RNStatusBar.currentHeight || 24) + 8 : 0,
  },

  // ── Home ──
  homeScroll: { paddingHorizontal: 20, paddingBottom: 48, paddingTop: 4 },

  homeHeader: { alignItems: 'center', paddingVertical: 16 },
  headerTopRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  themeToggle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  themeToggleIcon: { fontSize: 20 },

  badgeRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  badge: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
  },
  badgeText: { fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },

  homeTitle: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 36,
    letterSpacing: -0.5,
  },
  homeSubtitle: {
    fontSize: 13,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 18,
  },

  // ── Stats ──
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  statCard: {
    flex: 1,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    elevation: 2,
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  statIcon: { fontSize: 20, marginBottom: 4 },
  statNumber: { fontSize: 26, fontWeight: '800' },
  statLabel: { fontSize: 10, marginTop: 2, fontWeight: '700', letterSpacing: 0.5 },

  // ── Last Auth Card ──
  authResultCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 18,
    borderWidth: 1,
  },
  authResultHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  authResultBadge: { fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  authResultMatch: { fontSize: 11, fontWeight: '700' },
  authResultName: { fontSize: 20, fontWeight: '800' },
  authResultMeta: { fontSize: 12, marginTop: 4 },

  // ── Primary Button ──
  primaryBtn: {
    borderRadius: 20,
    marginBottom: 12,
    overflow: 'hidden',
    elevation: 8,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
  },
  primaryBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    gap: 14,
  },
  primaryBtnIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtnIcon: { fontSize: 26 },
  primaryBtnTextWrap: { flex: 1 },
  primaryBtnTitle: { color: '#FFF', fontSize: 18, fontWeight: '800' },
  primaryBtnSub: { color: 'rgba(255,255,255,0.75)', fontSize: 12, marginTop: 2 },
  primaryBtnArrow: { color: 'rgba(255,255,255,0.5)', fontSize: 32, fontWeight: '300' },

  // ── Secondary Button ──
  secondaryBtn: {
    borderRadius: 16,
    padding: 17,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
    borderWidth: 1,
  },
  secondaryBtnIcon: { fontSize: 18 },
  secondaryBtnText: { fontSize: 16, fontWeight: '700' },

  // ── Nav Grid ──
  navGrid: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  navCard: {
    flex: 1,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
  },
  navCardIcon: { fontSize: 22, marginBottom: 6 },
  navCardTitle: { fontSize: 12, fontWeight: '700' },
  navCardSub: { fontSize: 10, marginTop: 3, fontWeight: '600' },

  // ── Model Stats Card ──
  modelCard: {
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  modelCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  modelCardTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  modelBadge: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
  },
  modelBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  modelName: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 3,
  },
  modelDataset: {
    fontSize: 11,
    marginBottom: 14,
  },
  modelMetricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 12,
  },
  metricCell: {
    width: (SCREEN_W - 40 - 36 - 16) / 3,
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
  },
  metricCellValue: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  metricCellLabel: {
    fontSize: 9,
    fontWeight: '700',
    marginTop: 3,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  modelArch: {
    fontSize: 11,
    marginTop: 2,
  },

  // ── Security Grid ──
  securityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 12,
  },
  securityItem: {
    width: '48%',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    gap: 4,
  },
  securityIcon: { fontSize: 24 },
  securityTitle: { fontSize: 13, fontWeight: '800' },
  securityDesc: { fontSize: 10, fontWeight: '600' },

  // ── Pipeline Visual ──
  pipelineVisual: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    gap: 4,
  },
  pipelineStep: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  pipelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginBottom: 2,
  },
  pipelineLabel: {
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  pipelineSublabel: {
    fontSize: 9,
    fontWeight: '600',
    textAlign: 'center',
  },
  pipelineArrowText: {
    fontSize: 18,
    fontWeight: '300',
    marginBottom: 10,
  },

  // ── Integration Steps ──
  integrationSteps: {
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    gap: 8,
  },
  integrationStepText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
  },

  // ── Checklist ──
  checklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
  },
  checklistDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checklistCheck: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '800',
  },
  checklistLabel: {
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },

  // ── Footer ──
  footerCard: {
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
  },
  footerTitle: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5 },
  footerSub: { fontSize: 11, marginTop: 4, textAlign: 'center' },

  // ── Camera Cancel Button ──
  floatingCancel: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : (RNStatusBar.currentHeight || 24) + 12,
    right: 20,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  floatingCancelText: { color: '#FFF', fontSize: 16, fontWeight: '700' },

  // ── Screen Header ──
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerBack: { width: 72 },
  headerBackText: { fontSize: 15, fontWeight: '600' },
  screenTitle: { flex: 1, textAlign: 'center', fontSize: 16, fontWeight: '800' },
  headerRight: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    width: 72,
    alignItems: 'center',
  },
  headerRightText: { color: '#FFF', fontWeight: '800', fontSize: 11 },

  // ── Summary strip (attendance screen) ──
  summaryStrip: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 8,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
  },
  summaryItem: { flex: 1, alignItems: 'center', paddingVertical: 14 },
  summaryDivider: { width: 1 },
  summaryNumber: { fontSize: 22, fontWeight: '800' },
  summaryLabel: { fontSize: 10, marginTop: 2, fontWeight: '700' },

  // ── Sync Strip (attendance screen) ──
  syncStrip: {
    marginHorizontal: 16,
    marginBottom: 6,
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 9,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  syncStripText: { fontSize: 12, fontWeight: '700' },

  // ── List Content ──
  listContent: { padding: 16, paddingBottom: 32 },

  // ── Log Cards ──
  logCard: {
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    gap: 12,
  },
  logCardAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  logCardAvatarText: { color: '#FFF', fontSize: 18, fontWeight: '800' },
  logCardBody: { flex: 1 },
  logName: { fontSize: 15, fontWeight: '700' },
  logId: { fontSize: 11, marginTop: 2 },
  logLocation: { fontSize: 11, marginTop: 2 },
  logCardRight: { alignItems: 'flex-end', flexShrink: 0 },
  logTime: { fontSize: 15, fontWeight: '800' },
  logDate: { fontSize: 10, marginTop: 2 },
  syncBadge: {
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginTop: 6,
  },
  syncBadgeText: { color: '#FFF', fontSize: 9, fontWeight: '800' },

  // ── User Cards ──
  userCard: {
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    gap: 12,
  },
  userAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  userAvatarText: { color: '#FFF', fontSize: 22, fontWeight: '800' },
  userInfo: { flex: 1 },
  userName: { fontSize: 16, fontWeight: '800' },
  userId: { fontSize: 12, marginTop: 2 },
  userDate: { fontSize: 11, marginTop: 2 },
  deleteBtn: { padding: 6 },
  deleteBtnText: { fontSize: 22 },

  // ── Danger Zone ──
  dangerZone: { padding: 16, paddingBottom: 32 },
  dangerBtn: {
    borderRadius: 14,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.4)',
    backgroundColor: 'rgba(239,68,68,0.07)',
  },
  dangerBtnText: { color: '#DC2626', fontWeight: '700', fontSize: 14 },

  // ── Empty State ──
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    marginTop: 60,
  },
  emptyIcon: { fontSize: 56, marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: '700' },
  emptySub: { fontSize: 13, marginTop: 8, textAlign: 'center', lineHeight: 19 },

  // ── Registration Modal ──
  modalKAV: { flex: 1, justifyContent: 'flex-end' },
  modalScrim: { flex: 1 },
  modalSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 28,
    paddingBottom: Platform.OS === 'ios' ? 44 : 32,
    borderTopWidth: 1,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 22,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  modalInput: {
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    marginBottom: 18,
    borderWidth: 1,
  },
  modalBtn: {
    borderRadius: 16,
    padding: 17,
    alignItems: 'center',
    marginTop: 4,
    elevation: 4,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  modalBtnDisabled: { opacity: 0.4 },
  modalBtnText: { color: '#FFF', fontWeight: '800', fontSize: 16 },
  modalCancelBtn: { alignItems: 'center', padding: 14 },
  modalCancelText: { fontSize: 14, fontWeight: '600' },
});
